# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e9492363a618784d6d9bd03dbbef0d74cfd7b558ef367306d707393de2fc15a671c9174f42eeb8d0a87889608055a07f1c849dccbacac3b07dd2d6f5961400e

test:
  secret_key_base: 5c4c4ee23622a750c258f04e1f03d32256ed6f38fa2d1626b869c270ecd21edda61ad9d2c3f830e9accfc367daef4ff9c7d18569476d9d27d053a3002881d2b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
